classdef N9344C < Analysers.KEYSIGHT

    methods
        function obj = N9344C(~, args)
            obj@Analysers.KEYSIGHT('N9344C', args)
        end

        function startUp(obj)
            anl = tcpclient( obj.prop('ip'), double(obj.prop('port')) );
            writeline(anl, "" + ...
                "*CLS;" + ...
                ":INSTrument SA;" + ...
                ":FORMat:DATA REAL;" + ...
                ":AVERage:TYPE VOLT;" + ...
                ":SYSTem:CONFigure:GPS 1" );

            res = writeread(anl, ":SYSTEM:ERROR?");
            if ~contains(res, "No error", "IgnoreCase", true)
                warning("KEYSIGHT N9344C: StartUp: " + res)
            else
                disp("KEYSIGHT N9344C: Start Ok.")
            end
        end

        function out = getParms(obj)
            Sout = getParms@Analysers.KEYSIGHT(obj);
            lkeys = [
                "TraceMode"...
                "AvgTrace1State"...
                "AvgTrace1Count"...
                "DetectorTrace1Func"...
                "UnitPower"...
                "PowerRfHSensitive"
                ];
            res = obj.getCMD("" + ...
                ":TRACe1:MODE?;" + ...
                ":AVERage:TRACe1:STATe?;" + ...
                ":AVERage:TRACe1:COUNt?;" + ...
                ":DETector:TRACe1:FUNCtion?;" + ...
                ":UNIT:POWer?;" + ...
                ":POWer:RF:HSENsitive?;" ...
                );
            data = strsplit(res, ';');
            LocalOut = dictionary(lkeys, data);
            kout = [ keys(Sout), keys(LocalOut) ];
            vout = [ values(Sout), values(LocalOut) ];
            % Une as propriedades locais com a da superclasse
            out = dictionary( kout, vout );
        end
    end
end