classdef N9936B < Analysers.KEYSIGHT

    methods
        function obj = N9936B(~, args)
            obj@Analysers.KEYSIGHT('N9936B', args)
        end

        function startUp(obj)
            anl = tcpclient( obj.prop('ip'), double(obj.prop('port')) );
            writeline(anl, '' + ...
                '*CLS;' + ...
                ':INSTrument \"SA\";' + ...
                ':FORMat:DATA REAL,32;' + ...
                ':AVERage:TYPE VOLT;' + ...
                ':DISP:WIND:TRAC1:Y:AUTO;' + ...
                ':SYSTem:GPS:STATe INT' );

            res = writeread(anl, ":SYSTEM:ERROR?");
            if ~contains(res, "No error", "IgnoreCase", true)
                warning("KEYSIGHT N9936B: StartUp: " + res)
            else
                disp("KEYSIGHT N9936B: Start Ok.")
            end
        end

        function out = getParms(obj)
            Sout = getParms@Analysers.KEYSIGHT(obj);
            lkeys = [
                "TraceType"...
                "AvgCount"...
                "DetectFunc"...
                "AmplUnit"...
                "SweepPoints"...
                "RFGain"...
                "SweepAquisitionStatus"
                ];
            res = obj.getCMD("" + ...
                ":TRACe1:TYPE?;" + ...
                ":AVERage:COUNt?;" + ...
                ":DETector:FUNCtion?;" + ...
                ":AMPLitude:UNIT?;" + ...
                ":SWEep:POINTS?;" + ...
                ":POWer:RF:GAIN?;" + ...
                ":SWEep:ACQuisition:AUTO?;" ... 
                );
            data = strsplit(res, ';');
            LocalOut = dictionary(lkeys, data);
            kout = [ keys(Sout), keys(LocalOut) ];
            vout = [ values(Sout), values(LocalOut) ];
            % Une as propriedades locais com a da superclasse
            out = dictionary( kout, vout );
        end
    end
end